#!/bin/bash

PATH=$PATH:Tooling/swift-format/.build/release/
case $1 in
    setup)
        git config core.hooksPath Tooling/hooks
        git submodule update --init --recursive
        cd Tooling/swift-format && swift build -c release
        ;;
    format)
        if [ -z "$2" ]; then
            swift-format --in-place --recursive --configuration Tooling/formatterrc.json "Popcorn"
        else
            swift-format --in-place --configuration Tooling/formatterrc.json ${@:2}
        fi
        ;;
    sformat)
        swift-format ${@:2}
        ;;
    test)
        xcodebuild clean test -project Popcorn/Popcorn.xcodeproj -scheme Popcorn -destination 'platform=iOS Simulator,OS=13.3,name=iPad Pro (11-inch)'
        ;;
    *)
        echo "Invalid command."
        ;;
esac

