#!/bin/bash

PATH=$PATH:Tooling/swift-format/.build/release/
case $1 in
    setup)
        git config core.hooksPath Tooling/hooks
        ;;
    format)
        if [ -z "$2" ]; then
            swiftformat "Popcorn"
        else
            swiftformat ${@:2}
        fi
        ;;
    sformat)
        swift-format ${@:2}
        ;;
    test)
        xcodebuild clean test -project Popcorn/Popcorn.xcodeproj -scheme Popcorn -destination 'platform=iOS Simulator,OS=13.3,name=iPad Pro (11-inch)'
        ;;
    *)
        echo "Invalid command."
        ;;
esac

