name: Lint & Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    lint:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Lint
          run: |
              brew install swiftformat
              brew install swiftlint
              ./inferno lint

    test:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build & Test
          run: |
              ./inferno test
